### ISSUE TITLE
Crash in web version

### ISSUE THREAD

**Issue by Laiksion** [susoferreira/maquina-sencilla#1]
![image](https://github.com/susoferreira/maquina-sencilla/assets/74372467/6a6796ab-992e-41f0-9e62-40cb4b1b91df)
![image](https://github.com/susoferreira/maquina-sencilla/assets/74372467/57e84217-cf31-4dd9-8023-8be2fb442a9e)

**Comment by susoferreira** [comment]
Cannot reproduce
